name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r lint/requirements.txt
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install mdl

      - name: Files are UTF-8
        run: ./lint/encoding.sh .
      - name: "No non-breaking spaces"
        run: |
          if grep -rI --include='*.md' $'\u00A0' .; then
            exit 1
          fi
      - name: "No zero-width spaces"
        run: |
          if grep -rI --include='*.md' $'\u200B' .; then
            exit 1
          fi
      - name: "No carriage return"
        run: |
          if grep -rI --include='*.md' $'\u000D' .; then
            exit 1
          fi
      - name: "GitHub/JavaScript/TypeScript capitalized properly"
        run: |
          if grep -rI --include='*.md' -E "Github|Javascript|Typescript" .; then
            exit 1
          fi

      - name: Lint Markdown
        run: mdl . --ignore-front-matter -r MD003,MD005,MD011,MD018,MD019,MD023,MD025,MD027,MD028,MD030,MD035,MD037,MD038,MD039,MD046,MD047
      - name: Lint frontmatter
        run: ./lint/frontmatter.py .
