package(default_visibility = ["//visibility:private"])

cc_test(
  name = "test_types_operations",
  size = "small",
  srcs = ["types_operations.cpp"],
  deps = ["@com_google_googletest//:gtest_main"],
)
