name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04

    steps:
      # Installs missing package for the default C++ clangd toolchain for Bazel
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libtinfo5
          version: 1.0
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v4.0.0
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v4

      # build
      - name: Build the code
        run: bazel build //...

      # test
      - name: Test the code
        run: bazel test //...